### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by KevinBlack** [zhangmrit/ruoyi-ant#3]
如果不想要原本的页面，应该怎么删掉呢？

**Comment by zhangmrit** [comment]
比如呢？一般来说删除对应的组件，去掉路由就好了

**Comment by KevinBlack** [comment]
我现在的做法是在router.config.js文件中注释掉不想要的路由(例如只保留dashboard下的页面，其余的全部注释掉)，同时在 routerUtil.js文件中注释掉对应的路由(同样也只保留dashboard下的页面)，全过程没删任何组件或文件，可是运行项目时左侧菜单栏还是能看到那些本应被注释掉的东东……

**Comment by zhangmrit** [comment]
router.config.js该文件并未使用，只是用来做参考，routerUtil.js删除以后就好了啊
