### ISSUE TITLE
添加完动态路由后，next方法匹配不到路由会白屏不会匹配到*跳转404

### ISSUE THREAD

**Issue by xiaolisheng** [zhangmrit/ruoyi-ant#6]
**Describe the bug （描述 Bug）**
添加完动态路由后，next方法匹配不到路由会白屏不会匹配到*跳转404

**To Reproduce （重现步骤）**
1、登录跳转push一个不存在的路由
2、接着就会白屏

**Code Here**
原作者代码
```javascript
if (to.path === redirect) {
  // hack方法 确保addRoutes已完成 ,set the replace: true so the navigation will not leave a history record
  next({ ...to, replace: true });
} else {
  // 跳转到目的路由
  next({ path: redirect });
}
```
更改后代码
```javascript
router.push({path:redirect})
```

**Expected behavior（你期待的是什么?）**
期待作者能解释一下next方法和push方法的区别

**Comment by zhangmrit** [comment]
next是router.beforeEach((to, from, next)的一个钩子方法，push是router.push，级别就不一样啊
