### ISSUE TITLE
组织架构-用户管理-用户不能挂父节点

### ISSUE THREAD

**Issue by happydele** [zhangmrit/ruoyi-ant#8]
![微信图片_20200302105954](https://user-images.githubusercontent.com/49010750/75642039-1c109800-5c75-11ea-821c-edb99d79192a.jpg)

请问一下，当时优化这个问题，用户不能挂父节点，是基于什么原因考虑的？

如果我把这个限制打开有什么影响呢？
谢谢

**Comment by happydele** [comment]
更新日志
1.0.0-SNAPSHOT 2019-07-25

用户管理部门不应该选中父节点

**Comment by zhangmrit** [comment]
原版若依就是不能选择的，就算打开也不影响
